# Generated by Django 3.2.6 on 2021-08-15 04:17

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ingrdients', models.CharField(default=builtins.any, max_length=50)),
                ('submitted_by', models.ManyToManyField(related_name='Vendors', to='app.Vendors')),
            ],
        ),
    ]
